[POC] Manifest mode CI
mixxxdj/vcpkg pull request #34
Opened 2021-11-20 13:06 UTC by daschuer

This demonstrates how a Manifest mode CI will work. 
I consider this right now free of hacks around the vcpkg system, it just works. 

Advantages: 
* Upload to GitHub packages 
* Works on the contributors repro
* Maintains in place failure notification 
* Optional provides the binary blob, that people can use independent from a GitHub Account.

2021-11-20 14:03 UTC, Be-ing requested changes
This is duplicated code, both in the GitHub Actions workflow file and the vcpkg.json file, for no good reason.

2021-11-20 14:06 UTC, Be-ing commented
> Works on the contributors repro

This is false. GITHUB_TOKEN only has write access on the mixxxdj repos.

2021-11-20 14:07 UTC, Be-ing commented
> Optional provides the binary blob, that people can use independent from a GitHub Account.

Also false as already discussed in #29 and you can verify yourself.

2021-11-20 14:10 UTC, Be-ing commented
Please close this.

2021-11-20 14:15 UTC, Be-ing commented
This is an inflammatory action and you know it.

2021-11-20 15:30 UTC, daschuer commented
>> Works on the contributors repro

> This is false. GITHUB_TOKEN only has write access on the mixxxdj repos.

In case of a PR this is the token of the contributors repro. It is required to have read access to the packages of the mixxxdj repro. 

You can verify that it works by the 100 % cache hits of the windows build (48 s) :-)

2021-11-20 15:33 UTC, daschuer commented
>>  Optional provides the binary blob, that people can use independent from a GitHub Account.

> Also false as already discussed in #29 and you can verify yourself.

I have already verified it using meld and explained it here: https://github.com/mixxxdj/vcpkg/pull/29#issuecomment-974647095
Why do you keep saying that my assumption is false?

2021-11-20 15:33 UTC, Be-ing commented
>  Why do you keep saying that my assumption is false?

This is [sealioning](https://en.wikipedia.org/wiki/Sealioning).

2021-11-20 15:39 UTC, daschuer commented
> This is an inflammatory action and you know it.

No, sorry. You have already requested a vote. And for from you list of arguments against my opinion I got the impression you did not have understand my idea. This is here just the prove of concept. I think it is fair to present both options in an equal way that we can discuss along them and find finally the best solution. This works the best by tweaking one solution that both parties are satisfied. Overruling someone else by a vote should be the last resort.

2021-11-20 23:45 UTC, Be-ing commented
I understand your idea and I already voiced my objections before you opened this PR. I get the impression you either you either refuse to read the vcpkg documentation or choose to ignore it. If you have an objection to how vcpkg is designed, the appropriate place to debate that is upstream.

2021-11-21 01:19 UTC, Be-ing commented
https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md

> In manifest mode, an installed tree is associated with a particular project rather than the vcpkg installation. The set of installed ports is controlled by editing the project's "manifest file", and the installed tree is placed in the project directory or build directory. This mode acts more similarly to language package managers like Cargo, or npm. We recommend using this manifest mode whenever possible, because it allows one to encode a project's dependencies explicitly in a project file, rather than in the documentation, making your project much easier to consume.

> Our CMake Integration will automatically detect a vcpkg.json manifest file in the same directory as the top-level CMakeLists.txt (${CMAKE_SOURCE_DIR}/vcpkg.json) and activate manifest mode. Vcpkg will be automatically bootstrapped if missing and invoked to install your dependencies into your local build directory (${CMAKE_BINARY_DIR}/vcpkg_installed).

2021-11-21 10:29 UTC, daschuer commented
This PR does not fight the vcpkg design if the Mixxx repo at all and is unrelated. I acknowledge that we should follow the vpkg design as described. 

This PR is a solution for maintaining a CI in the our vcpkg branch, which allows a streamlined development workflow. Even upstream has a CI. Our mixxx/vcpkg repro is already associated with the mixxx project.

In a comparison with cargo, it is not true that it is similar. A cargo.toml is a self contained manifest file were the packages inclusive versions are referenced.

Or approach here is different. The vcpkg.json contains only the packages name. The version comes via the strong commit hash reference from our mixxxdj/vcpkg repro. 

I am not sure if it is possible to move completely to the cargo approach and replace the strong commit hash reference by a package version based approach like in cargo. I would welcome that.

2021-11-21 12:35 UTC, Be-ing commented
Making comparisons to things you don't understand does not strengthen your argument.

2021-11-21 12:45 UTC, Be-ing commented
> This PR does not fight the vcpkg design if the Mixxx repo at all and is unrelated.

It is 100% related. You are creating code duplication.

2023-08-15 20:44 UTC, closed without merging